// GENERATED by contract/codegen.mjs — edit contract/*.json instead, then
// run `npm run contract:gen` from the repo root.
import type { LayoutTemplate, LayoutZones } from '../types'

export const WAVE_BARS = 64 as const
export const BAR_FILL = 0.64 as const
export const GAP_FILL = 0.36 as const
export const EQ_BANDS = 40 as const
export const EQ_BPS = 30 as const
export const WAVE_BPS = 120 as const
export const BG_DARK_TOP = 0.22 as const
export const BG_DARK_BOTTOM = 0.5 as const
export const SPLIT_BPS = 30 as const

export const DEFAULT_ZONES: Record<LayoutTemplate, LayoutZones> = {
  spotify: {
    waveform: { x: 0.04, y: 0.6, w: 0.92, h: 0.22 },
    title: { x: 0.1, y: 0.44, w: 0.8, h: 0.12 },
    avatar: { x: 0.32, y: 0.08, w: 0.36, h: 0.36 },
    subtitle: { x: 0.04, y: 0.85, w: 0.92, h: 0.1 },
  },
  split: {
    waveform: { x: 0.55, y: 0.42, w: 0.41, h: 0.3 },
    title: { x: 0.55, y: 0.14, w: 0.4, h: 0.16 },
    avatar: { x: 0, y: 0, w: 0.5, h: 1 },
    subtitle: { x: 0.55, y: 0.8, w: 0.41, h: 0.1 },
  },
  minimal: {
    waveform: { x: 0.02, y: 0.3, w: 0.96, h: 0.36 },
    title: { x: 0.08, y: 0.05, w: 0.84, h: 0.16 },
    subtitle: { x: 0.04, y: 0.74, w: 0.92, h: 0.1 },
  },
  fullbg: {
    waveform: { x: 0.04, y: 0.6, w: 0.92, h: 0.2 },
    title: { x: 0.1, y: 0.36, w: 0.8, h: 0.12 },
    avatar: { x: 0.35, y: 0.07, w: 0.3, h: 0.3 },
    subtitle: { x: 0.04, y: 0.83, w: 0.92, h: 0.1 },
  },
  karaoke: {
    waveform: { x: 0.04, y: 0.78, w: 0.92, h: 0.1 },
    title: { x: 0.06, y: 0.22, w: 0.88, h: 0.56 },
  },
  brand: {
    waveform: { x: 0.55, y: 0.12, w: 0.42, h: 0.76 },
    title: { x: 0.24, y: 0.36, w: 0.32, h: 0.28 },
    avatar: { x: 0.04, y: 0.36, w: 0.16, h: 0.28 },
  },
}
