#!/usr/bin/env node
// contract/codegen.mjs — TECH_ARCHITECTURE.md §2.4a / PHASE1_TASKS.md T14.
//
// Reads contract/constants.json + contract/zones.json (the one hand-edited
// source of truth) and writes two generated files:
//   packages/contract/src/index.ts
//   crates/audiogram-core/src/contract_gen.rs
//
// The TS output lives in packages/contract (T17) so both the app and
// @audiogram/wave-effects can depend on it as a real npm workspace package
// instead of a relative path into the app — which means it can't import
// LayoutZone/LayoutZones/LayoutTemplate from apps/desktop/src/types.ts
// (that'd be a package depending on its own consumer); it declares its own
// copies of those 3 shapes instead. apps/desktop/src/types.ts still owns the
// hand-written versions component code imports — TS's structural typing
// means both just need to agree on shape, not share a declaration.
//
// The Rust output lives in audiogram-core (not the app crate) since T16
// moved it there — audiogram-render and audiogram-subtitle both need these
// constants and can't depend on the app crate (that'd be a cycle).
//
// Both are committed to the repo (not gitignored) and regenerated by this
// script, not by Rust's build.rs — build.rs can't depend on node, so the
// .rs output is plain checked-in source plus a #[test] that keeps it
// honest (PHASE1_TASKS.md T14 step 3).
//
// NOTE: PHASE1_TASKS.md's T14 constant list includes `INTRO_DURATION`, but
// no such constant exists anywhere in the current TS or Rust source (grepped
// both trees before writing constants.json) — it looks like it describes a
// not-yet-implemented feature. Omitted here rather than inventing a value;
// see the p1-t14 commit message.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '..')

const rawConstants = JSON.parse(readFileSync(path.join(here, 'constants.json'), 'utf8'))
const zones = JSON.parse(readFileSync(path.join(here, 'zones.json'), 'utf8'))
const text = JSON.parse(readFileSync(path.join(here, 'text.json'), 'utf8'))
const sceneSchema = JSON.parse(readFileSync(path.join(here, 'scene_schema.json'), 'utf8'))

// text.json's keys are camelCase (titleMaxLines) since they read naturally
// that way in JSON; every other constant in this file is SCREAMING_SNAKE, so
// convert here rather than mixing conventions across the two generated
// modules (PHASE3_TASKS.md T5).
function camelToScreamingSnake(key) {
  return key.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()
}

const constants = {
  ...rawConstants,
  ...Object.fromEntries(Object.entries(text).map(([k, v]) => [camelToScreamingSnake(k), v])),
}

// Matches LAYOUT_TEMPLATES' order in apps/desktop/src/types.ts, purely so
// generated output has a stable, human-reviewable diff.
const TEMPLATE_ORDER = ['spotify', 'split', 'minimal', 'fullbg', 'karaoke', 'brand']
const REQUIRED_ZONE_KEYS = ['waveform', 'title']
const OPTIONAL_ZONE_KEYS = ['avatar', 'subtitle']

// Rust integer types per constant — anything not listed here (BAR_FILL,
// GAP_FILL, BG_DARK_TOP, BG_DARK_BOTTOM) is f32.
const RUST_INT_TYPE = {
  WAVE_BARS: 'usize', EQ_BANDS: 'usize', EQ_BPS: 'u32', WAVE_BPS: 'usize', SPLIT_BPS: 'usize',
  TITLE_MAX_LINES: 'usize', SUBTITLE_MAX_LINES: 'usize',
}

function rustType(key) {
  return RUST_INT_TYPE[key] ?? 'f32'
}

/** A JS number formatted as a valid Rust f32 literal — Rust's integer and
 * float literal syntaxes don't unify (unlike `let x: f32 = 0`, which is
 * *also* invalid), so an integer-valued float needs an explicit `.0`
 * wherever it lands in f32-typed position: a top-level const or a
 * LayoutZone field. */
function rustFloat(value) {
  return Number.isInteger(value) ? `${value}.0` : String(value)
}

function rustLiteral(key, value) {
  return rustType(key) === 'f32' ? rustFloat(value) : String(value)
}

function tsConstLine([key, value]) {
  return `export const ${key} = ${value} as const`
}

function tsZone(zone) {
  return `{ x: ${zone.x}, y: ${zone.y}, w: ${zone.w}, h: ${zone.h} }`
}

function genTs() {
  const constLines = Object.entries(constants).map(tsConstLine).join('\n')
  const zoneEntries = TEMPLATE_ORDER.map(id => {
    const z = zones[id]
    const fields = [...REQUIRED_ZONE_KEYS, ...OPTIONAL_ZONE_KEYS]
      .filter(k => z[k])
      .map(k => `    ${k}: ${tsZone(z[k])},`)
      .join('\n')
    return `  ${id}: {\n${fields}\n  },`
  }).join('\n')

  return `// GENERATED by contract/codegen.mjs — edit contract/*.json instead, then
// run \`npm run contract:gen\` from the repo root.

${constLines}

// Structurally identical to apps/desktop/src/types.ts's hand-written
// LayoutZone/LayoutZones/LayoutTemplate — this package can't import those
// (see the file header), so TS's structural typing carries the contract
// instead of a shared declaration.
export interface LayoutZone {
  x: number
  y: number
  w: number
  h: number
}

export interface LayoutZones {
  waveform: LayoutZone
  title: LayoutZone
  avatar?: LayoutZone
  subtitle?: LayoutZone
}

export type LayoutTemplate = ${TEMPLATE_ORDER.map(id => `'${id}'`).join(' | ')}

export const DEFAULT_ZONES: Record<LayoutTemplate, LayoutZones> = {
${zoneEntries}
}
`
}

function rustConstLine([key, value]) {
  return `pub const ${key}: ${rustType(key)} = ${rustLiteral(key, value)};`
}

function rustRequiredZone(zone) {
  return `LayoutZone { x: ${rustFloat(zone.x)}, y: ${rustFloat(zone.y)}, w: ${rustFloat(zone.w)}, h: ${rustFloat(zone.h)} }`
}

function rustOptionalZone(zone) {
  return zone ? `Some(${rustRequiredZone(zone)})` : 'None'
}

function genRust() {
  const constLines = Object.entries(constants).map(rustConstLine).join('\n')

  const matchArms = TEMPLATE_ORDER.map(id => {
    const z = zones[id]
    const requiredFields = REQUIRED_ZONE_KEYS.map(k => `            ${k}: ${rustRequiredZone(z[k])},`).join('\n')
    const optionalFields = OPTIONAL_ZONE_KEYS.map(k => `            ${k}: ${rustOptionalZone(z[k])},`).join('\n')
    return `        "${id}" => LayoutZones {\n${requiredFields}\n${optionalFields}\n        },`
  }).join('\n')

  const assertLines = Object.entries(constants)
    .map(([key, value]) => `        assert_eq!(${key}, ${rustLiteral(key, value)});`)
    .join('\n')

  return `// GENERATED by contract/codegen.mjs — edit contract/*.json instead, then
// run \`npm run contract:gen\` from the repo root.
#![allow(dead_code)]

use serde::Deserialize;
use specta::Type;

${constLines}

#[derive(Debug, Clone, Copy, PartialEq, Deserialize, Type)]
pub struct LayoutZone {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

#[derive(Debug, Clone, Copy, PartialEq, Deserialize, Type)]
pub struct LayoutZones {
    pub waveform: LayoutZone,
    pub title: LayoutZone,
    pub avatar: Option<LayoutZone>,
    pub subtitle: Option<LayoutZone>,
}

/// Mirrors apps/desktop/src/types.ts's DEFAULT_ZONES. Consumed by
/// RenderJob's TryFrom (crates/audiogram-core/src/entities/render_job.rs)
/// as the fallback when a RenderJobDto arrives with no zones override — the
/// frame renderer itself reads whichever LayoutZones ends up on RenderJob,
/// never calls this directly (PHASE3_TASKS.md T2).
pub fn default_zones(template: &str) -> Option<LayoutZones> {
    Some(match template {
${matchArms}
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_gen_is_fresh() {
${assertLines}
    }
}
`
}

function genSceneTs() {
  const { nodeTypes, animationPresets, easingTypes, keyframeProperties, textRoles, imageFitOptions, imageShapeOptions, textAlignOptions } = sceneSchema

  const nodeTypeUnion = nodeTypes.map(t => `'${t}'`).join(' | ')
  const animIdUnion = animationPresets.map(t => `'${t}'`).join(' | ')
  const easingUnion = easingTypes.map(t => `'${t}'`).join(' | ')
  const keyframePropUnion = keyframeProperties.map(t => `'${t}'`).join(' | ')
  const textRoleUnion = textRoles.map(t => `'${t}'`).join(' | ')
  const fitUnion = imageFitOptions.map(t => `'${t}'`).join(' | ')
  const shapeUnion = imageShapeOptions.map(t => `'${t}'`).join(' | ')
  const alignUnion = textAlignOptions.map(t => `'${t}'`).join(' | ')

  return `// GENERATED by contract/codegen.mjs — edit contract/scene_schema.json instead,
// then run \`npm run contract:gen\` from the repo root.
// Imported by apps/desktop/src/types.ts and packages/wave-effects as needed.

// ── Core geometry ──────────────────────────────────────────────────────────

export interface Transform {
  x: number        // fraction 0–1 of canvas width
  y: number        // fraction 0–1 of canvas height
  w: number        // fraction 0–1 of canvas width
  h: number        // fraction 0–1 of canvas height
  rotation?: number  // degrees, default 0
  opacity?: number   // 0–1, default 1
}

// ── Animation ──────────────────────────────────────────────────────────────

export type AnimationId = ${animIdUnion}
export type Easing = ${easingUnion}
export type KeyframeProperty = ${keyframePropUnion}

export interface AnimationClip {
  preset: AnimationId
  duration: number  // seconds
}

export interface Keyframe {
  t: number                 // absolute time in seconds
  value: number | string
  easing: Easing
}

export interface KeyframeTrack {
  property: KeyframeProperty
  keyframes: Keyframe[]
}

// ── Props per node type ────────────────────────────────────────────────────

export type TextRole = ${textRoleUnion}
export type ImageFit = ${fitUnion}
export type ImageShape = ${shapeUnion}
export type TextAlign = ${alignUnion}

export interface WaveformProps {
  style: string       // WaveStyle — kept as string to avoid circular dep with wave-effects
  color: string       // hex
}

export interface TextProps {
  text: string
  role: TextRole
  /** When true the node's text is replaced at render time by the active transcript segment.
   *  Used for captions — replaces the old libass burn-in path (Phase 5 T14). */
  boundToTranscript?: boolean
  color: string
  font: string
  size: number        // px at 1080p canvas height
  align: TextAlign
  bold: boolean
  italic: boolean
}

export interface ImageProps {
  src: string         // absolute path or app-scheme URL
  fit: ImageFit
  shape?: ImageShape
}

export interface StickerProps {
  assetId: string     // key into built-in sticker bundle (Phase 5 T15)
}

export interface VideoProps {
  src: string         // absolute path
  fit: ImageFit
  loop: boolean
  readonly muted: true  // always true — video background is decorative only
}

// ── The node ───────────────────────────────────────────────────────────────

export type SceneNodeType = ${nodeTypeUnion}

export type SceneNodeProps = WaveformProps | TextProps | ImageProps | StickerProps | VideoProps

export interface SceneNode {
  id: string
  type: SceneNodeType
  /** Id of parent group node. Absent = root level.
   *  Children are derived by \`nodes.filter(n => n.parentId === group.id)\`
   *  — no \`children[]\` array to avoid dual source-of-truth. */
  parentId?: string
  transform: Transform
  z: number
  /** Primary show/hide window. Absent = node is visible for the entire video. */
  timing?: { start: number; end: number }
  /** Entry animation, applied over [timing.start, timing.start + animIn.duration]. */
  animIn?: AnimationClip
  /** Exit animation, applied over [timing.end - animOut.duration, timing.end]. */
  animOut?: AnimationClip
  /** Advanced continuous property animation. NOT the mechanism for simple show/hide. */
  keyframes?: KeyframeTrack[]
  /** Absent for group nodes (groups only compose children transforms). */
  props?: SceneNodeProps
}
`
}

writeFileSync(path.join(repoRoot, 'packages/contract/src/index.ts'), genTs())
writeFileSync(path.join(repoRoot, 'crates/audiogram-core/src/contract_gen.rs'), genRust())
writeFileSync(path.join(repoRoot, 'packages/contract/src/scene.ts'), genSceneTs())

console.log('contract: wrote packages/contract/src/index.ts + crates/audiogram-core/src/contract_gen.rs + packages/contract/src/scene.ts')
