#!/usr/bin/env node
// contract/codegen.mjs — TECH_ARCHITECTURE.md §2.4a / PHASE1_TASKS.md T14.
//
// Reads contract/constants.json + contract/zones.json (the one hand-edited
// source of truth) and writes two generated files:
//   apps/desktop/src/domain/contract.gen.ts
//   crates/audiogram-core/src/contract_gen.rs
//
// The Rust output lives in audiogram-core (not the app crate) since T16
// moved it there — audiogram-render and audiogram-subtitle both need these
// constants and can't depend on the app crate (that'd be a cycle).
//
// Both are committed to the repo (not gitignored) and regenerated by this
// script, not by Rust's build.rs — build.rs can't depend on node, so the
// .rs output is plain checked-in source plus a #[test] that keeps it
// honest (PHASE1_TASKS.md T14 step 3).
//
// NOTE: PHASE1_TASKS.md's T14 constant list includes `INTRO_DURATION`, but
// no such constant exists anywhere in the current TS or Rust source (grepped
// both trees before writing constants.json) — it looks like it describes a
// not-yet-implemented feature. Omitted here rather than inventing a value;
// see the p1-t14 commit message.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '..')

const constants = JSON.parse(readFileSync(path.join(here, 'constants.json'), 'utf8'))
const zones = JSON.parse(readFileSync(path.join(here, 'zones.json'), 'utf8'))

// Matches LAYOUT_TEMPLATES' order in apps/desktop/src/types.ts, purely so
// generated output has a stable, human-reviewable diff.
const TEMPLATE_ORDER = ['spotify', 'split', 'minimal', 'fullbg', 'karaoke', 'brand']
const REQUIRED_ZONE_KEYS = ['waveform', 'title']
const OPTIONAL_ZONE_KEYS = ['avatar', 'subtitle']

// Rust integer types per constant — anything not listed here (BAR_FILL,
// GAP_FILL, BG_DARK_TOP, BG_DARK_BOTTOM) is f32.
const RUST_INT_TYPE = { WAVE_BARS: 'usize', EQ_BANDS: 'usize', EQ_BPS: 'u32', WAVE_BPS: 'usize', SPLIT_BPS: 'usize' }

function rustType(key) {
  return RUST_INT_TYPE[key] ?? 'f32'
}

/** A JS number formatted as a valid Rust f32 literal — Rust's integer and
 * float literal syntaxes don't unify (unlike `let x: f32 = 0`, which is
 * *also* invalid), so an integer-valued float needs an explicit `.0`
 * wherever it lands in f32-typed position: a top-level const or a
 * LayoutZone field. */
function rustFloat(value) {
  return Number.isInteger(value) ? `${value}.0` : String(value)
}

function rustLiteral(key, value) {
  return rustType(key) === 'f32' ? rustFloat(value) : String(value)
}

function tsConstLine([key, value]) {
  return `export const ${key} = ${value} as const`
}

function tsZone(zone) {
  return `{ x: ${zone.x}, y: ${zone.y}, w: ${zone.w}, h: ${zone.h} }`
}

function genTs() {
  const constLines = Object.entries(constants).map(tsConstLine).join('\n')
  const zoneEntries = TEMPLATE_ORDER.map(id => {
    const z = zones[id]
    const fields = [...REQUIRED_ZONE_KEYS, ...OPTIONAL_ZONE_KEYS]
      .filter(k => z[k])
      .map(k => `    ${k}: ${tsZone(z[k])},`)
      .join('\n')
    return `  ${id}: {\n${fields}\n  },`
  }).join('\n')

  return `// GENERATED by contract/codegen.mjs — edit contract/*.json instead, then
// run \`npm run contract:gen\` from the repo root.
import type { LayoutTemplate, LayoutZones } from '../types'

${constLines}

export const DEFAULT_ZONES: Record<LayoutTemplate, LayoutZones> = {
${zoneEntries}
}
`
}

function rustConstLine([key, value]) {
  return `pub const ${key}: ${rustType(key)} = ${rustLiteral(key, value)};`
}

function rustRequiredZone(zone) {
  return `LayoutZone { x: ${rustFloat(zone.x)}, y: ${rustFloat(zone.y)}, w: ${rustFloat(zone.w)}, h: ${rustFloat(zone.h)} }`
}

function rustOptionalZone(zone) {
  return zone ? `Some(${rustRequiredZone(zone)})` : 'None'
}

function genRust() {
  const constLines = Object.entries(constants).map(rustConstLine).join('\n')

  const matchArms = TEMPLATE_ORDER.map(id => {
    const z = zones[id]
    const requiredFields = REQUIRED_ZONE_KEYS.map(k => `            ${k}: ${rustRequiredZone(z[k])},`).join('\n')
    const optionalFields = OPTIONAL_ZONE_KEYS.map(k => `            ${k}: ${rustOptionalZone(z[k])},`).join('\n')
    return `        "${id}" => LayoutZones {\n${requiredFields}\n${optionalFields}\n        },`
  }).join('\n')

  const assertLines = Object.entries(constants)
    .map(([key, value]) => `        assert_eq!(${key}, ${rustLiteral(key, value)});`)
    .join('\n')

  return `// GENERATED by contract/codegen.mjs — edit contract/*.json instead, then
// run \`npm run contract:gen\` from the repo root.
#![allow(dead_code)]

${constLines}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutZone {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutZones {
    pub waveform: LayoutZone,
    pub title: LayoutZone,
    pub avatar: Option<LayoutZone>,
    pub subtitle: Option<LayoutZone>,
}

/// Mirrors apps/desktop/src/types.ts's DEFAULT_ZONES. Not consumed by the
/// frame renderer yet (it still hardcodes per-template geometry in its own
/// match arms — PHASE1_TASKS.md T14 only asks for the data to exist on both
/// sides, not to rewire frame.rs), but ready for a future pass that reads
/// zones dynamically instead.
pub fn default_zones(template: &str) -> Option<LayoutZones> {
    Some(match template {
${matchArms}
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_gen_is_fresh() {
${assertLines}
    }
}
`
}

writeFileSync(path.join(repoRoot, 'apps/desktop/src/domain/contract.gen.ts'), genTs())
writeFileSync(path.join(repoRoot, 'crates/audiogram-core/src/contract_gen.rs'), genRust())

console.log('contract: wrote apps/desktop/src/domain/contract.gen.ts + crates/audiogram-core/src/contract_gen.rs')
