// @ts-nocheck
// This file was generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping(name: string) : Promise<string> {
    return await TAURI_INVOKE("ping", { name });
},
async openFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderAudiogram(params: RenderJobDto) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_audiogram", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRender() : Promise<void> {
    await TAURI_INVOKE("cancel_render");
},
async resolveFfmpegPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_ffmpeg_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeSpectrum(audioPath: string) : Promise<Result<SpectrumResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_spectrum", { audioPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(audioPath: string, modelName: string | null) : Promise<Result<Segment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioPath, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeSrt(segments: Segment[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_srt", { segments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeAss(segments: Segment[], params: WriteAssParams) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_ass", { segments, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels() : Promise<ModelInfo[]> {
    return await TAURI_INVOKE("list_models");
},
async downloadModel(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Runtime representation including whether the model is downloaded — sent to the frontend.
 */
export type ModelInfo = { name: string; label: string; size_mb: number; note: string; downloaded: boolean }
/**
 * Raw DTO from Tauri IPC — mirrors the JS object sent by the frontend verbatim.
 */
export type RenderJobDto = { audio_path: string; peaks: number[]; bg_color: string; captions_path: string | null; width: number; height: number; fps: number; wave_color: string; wave_style: string; intro_title: string | null; font_size: number | null; font_name: string | null; layout_template: string | null; output_path: string }
export type Segment = { id: number; start: number; end: number; text: string }
export type SpectrumResult = { 
/**
 * Flat Vec<f32> of length `n_buckets × EQ_BANDS`.
 * Access: `bands[t * EQ_BANDS + b]` = amplitude of band b at time bucket t.
 */
bands: number[]; n_buckets: number; n_bands: number }
export type WriteAssParams = { highlightColor: string; videoWidth: number | null; videoHeight: number | null; fontSizePct: number | null; layoutTemplate: string | null; karaokeEnabled: boolean | null; fontName: string | null; subtitleYPct: number | null; subtitleColor: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
