// @ts-nocheck
// This file was generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping(name: string) : Promise<string> {
    return await TAURI_INVOKE("ping", { name });
},
async openFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderAudiogram(params: RenderJobDto) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_audiogram", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRender() : Promise<void> {
    await TAURI_INVOKE("cancel_render");
},
async resolveFfmpegPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_ffmpeg_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analyzeSpectrum(audioPath: string) : Promise<Result<SpectrumResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_spectrum", { audioPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(audioPath: string, modelName: string | null) : Promise<Result<Segment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioPath, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeSrt(segments: Segment[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_srt", { segments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeAss(segments: Segment[], params: WriteAssParams) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_ass", { segments, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels() : Promise<ModelInfo[]> {
    return await TAURI_INVOKE("list_models");
},
async downloadModel(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AnimationClip = { preset: AnimationId; duration: number }
/**
 * Mirrors `AnimationId` in scene.ts — keep in sync with scene_schema.json `animationPresets`.
 */
export type AnimationId = "fade" | "slide-up" | "slide-down" | "scale-in"
/**
 * Mirrors `Easing` in scene.ts — keep in sync with `easingTypes`.
 */
export type Easing = "linear" | "ease-in" | "ease-out" | "ease-in-out" | "hold"
export type Fit = "cover" | "contain"
export type ImageProps = { src: string; fit: Fit; shape: ImageShape | null }
export type ImageShape = "rect" | "circle" | "rounded"
export type Keyframe = { t: number; value: number; easing: Easing }
/**
 * Mirrors `KeyframeProperty` in scene.ts.
 */
export type KeyframeProperty = "x" | "y" | "w" | "h" | "rotation" | "opacity"
export type KeyframeTrack = { property: KeyframeProperty; keyframes: Keyframe[] }
export type LayoutZone = { x: number; y: number; w: number; h: number }
export type LayoutZones = { waveform: LayoutZone; title: LayoutZone; avatar: LayoutZone | null; subtitle: LayoutZone | null }
/**
 * Runtime representation including whether the model is downloaded — sent to the frontend.
 */
export type ModelInfo = { name: string; label: string; size_mb: number; note: string; downloaded: boolean }
/**
 * Raw DTO from Tauri IPC — mirrors the JS object sent by the frontend verbatim.
 */
export type RenderJobDto = { audio_path: string; peaks: number[]; bg_color: string; captions_path: string | null; width: number; height: number; fps: number; wave_color: string; wave_style: string; intro_title: string | null; font_size: number | null; font_name: string | null; layout_template: string | null; output_path: string; 
/**
 * Absolute path to the avatar/background image picked in StepLayout —
 * mirrors WaveformCanvas.tsx's `coverImagePath`. `None`/empty means no
 * image was chosen; the renderer falls back to its placeholder gradient.
 */
cover_image_path: string | null; 
/**
 * Zone override from the Design mode canvas stage (store.zones) — mirrors
 * the preview's `zones ?? DEFAULT_ZONES[layoutTemplate]` fallback exactly
 * (PHASE3_TASKS.md T2, fixes the frame renderer previously never reading
 * zones at all). `None` means the user hasn't dragged anything — RenderJob
 * falls back to `default_zones(layout)`, the same contract-generated data
 * the preview's DEFAULT_ZONES comes from.
 */
zones: LayoutZones | null; 
/**
 * Title text style — mirrors the store's `titleColor`/`titleAlign`/
 * `titleBold`/`titleItalic` (PHASE3_TASKS.md T4, fixes the title
 * inspector's controls being a no-op at export: the old ffmpeg
 * `drawtext` path hardcoded white text, fixed per-layout centering,
 * never bold/italic). `None` for each means the store's own default
 * (white / center / not bold / not italic).
 */
title_color: string | null; title_align: string | null; title_bold: boolean | null; title_italic: boolean | null; 
/**
 * Scene graph nodes (Phase 5 T5) — when present, the render pipeline
 * draws via `audiogram_render::scene_frame::render_scene_frame_into`
 * instead of the legacy `render_frame_into` layout match-arms. `None`
 * (the default — no frontend caller sets this yet outside the
 * `VITE_USE_NODE_RENDERER` flag) keeps the legacy export path
 * byte-identical to before this field existed (PHASE5_TASKS.md §A.6 —
 * this is the fix for the historical "zones never reached export" bug).
 */
nodes: SceneNode[] | null }
/**
 * A single composable element on the scene graph.
 * Mirrors `SceneNode` in packages/contract/src/scene.ts exactly.
 */
export type SceneNode = { id: string; type: SceneNodeType; 
/**
 * Id of parent group. `None` = root level.
 * Children derived by `nodes.iter().filter(|n| n.parent_id.as_deref() == Some(group_id))`.
 */
parentId: string | null; transform: Transform; z: number; timing: Timing | null; animIn: AnimationClip | null; animOut: AnimationClip | null; keyframes?: KeyframeTrack[]; props: SceneNodeProps | null }
/**
 * Discriminated union of all node prop variants.
 */
export type SceneNodeProps = ({ type: "waveform" } & WaveformProps) | ({ type: "text" } & TextProps) | ({ type: "image" } & ImageProps) | ({ type: "sticker" } & StickerProps) | ({ type: "video" } & VideoProps)
export type SceneNodeType = "waveform" | "text" | "image" | "sticker" | "video" | "group"
export type Segment = { id: number; start: number; end: number; text: string }
export type SpectrumResult = { 
/**
 * Flat Vec<f32> of length `n_buckets × EQ_BANDS`.
 * Access: `bands[t * EQ_BANDS + b]` = amplitude of band b at time bucket t.
 */
bands: number[]; n_buckets: number; n_bands: number }
export type StickerProps = { assetId: string }
export type TextAlign = "left" | "center" | "right"
export type TextProps = { text: string; role: TextRole; boundToTranscript?: boolean; color: string; font: string; size: number; align: TextAlign; bold: boolean; italic: boolean }
export type TextRole = "title" | "subtitle" | "caption" | "freeform"
export type Timing = { start: number; end: number }
/**
 * Canvas-fraction transform. All x/y/w/h are in [0, 1] relative to canvas size.
 * For a child of a group, these are fractions of the group's local space.
 */
export type Transform = { x: number; y: number; w: number; h: number; rotation?: number; opacity?: number }
export type VideoProps = { src: string; fit: Fit; loop: boolean; muted?: boolean }
export type WaveformProps = { style: string; color: string }
export type WriteAssParams = { highlightColor: string; videoWidth: number | null; videoHeight: number | null; fontSizePct: number | null; layoutTemplate: string | null; karaokeEnabled: boolean | null; fontName: string | null; subtitleYPct: number | null; subtitleColor: string | null; 
/**
 * Layout zones for subtitle positioning — passed from export sheet
 * (Phase 4 T2). When present, `zones.subtitle.y` is used for MarginV
 * in ASS style (instead of hard-coded per-layout fallback).
 */
zones: LayoutZones | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
