// GENERATED by contract/codegen.mjs — edit contract/*.json instead, then
// run `npm run contract:gen` from the repo root.
#![allow(dead_code)]

pub const WAVE_BARS: usize = 64;
pub const BAR_FILL: f32 = 0.64;
pub const GAP_FILL: f32 = 0.36;
pub const EQ_BANDS: usize = 40;
pub const EQ_BPS: u32 = 30;
pub const WAVE_BPS: usize = 120;
pub const BG_DARK_TOP: f32 = 0.22;
pub const BG_DARK_BOTTOM: f32 = 0.5;
pub const SPLIT_BPS: usize = 30;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutZone {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutZones {
    pub waveform: LayoutZone,
    pub title: LayoutZone,
    pub avatar: Option<LayoutZone>,
    pub subtitle: Option<LayoutZone>,
}

/// Mirrors apps/desktop/src/types.ts's DEFAULT_ZONES. Not consumed by the
/// frame renderer yet (it still hardcodes per-template geometry in its own
/// match arms — PHASE1_TASKS.md T14 only asks for the data to exist on both
/// sides, not to rewire frame.rs), but ready for a future pass that reads
/// zones dynamically instead.
pub fn default_zones(template: &str) -> Option<LayoutZones> {
    Some(match template {
        "spotify" => LayoutZones {
            waveform: LayoutZone { x: 0.04, y: 0.6, w: 0.92, h: 0.22 },
            title: LayoutZone { x: 0.1, y: 0.44, w: 0.8, h: 0.12 },
            avatar: Some(LayoutZone { x: 0.32, y: 0.08, w: 0.36, h: 0.36 }),
            subtitle: Some(LayoutZone { x: 0.04, y: 0.85, w: 0.92, h: 0.1 }),
        },
        "split" => LayoutZones {
            waveform: LayoutZone { x: 0.55, y: 0.42, w: 0.41, h: 0.3 },
            title: LayoutZone { x: 0.55, y: 0.14, w: 0.4, h: 0.16 },
            avatar: Some(LayoutZone { x: 0.0, y: 0.0, w: 0.5, h: 1.0 }),
            subtitle: Some(LayoutZone { x: 0.55, y: 0.8, w: 0.41, h: 0.1 }),
        },
        "minimal" => LayoutZones {
            waveform: LayoutZone { x: 0.02, y: 0.3, w: 0.96, h: 0.36 },
            title: LayoutZone { x: 0.08, y: 0.05, w: 0.84, h: 0.16 },
            avatar: None,
            subtitle: Some(LayoutZone { x: 0.04, y: 0.74, w: 0.92, h: 0.1 }),
        },
        "fullbg" => LayoutZones {
            waveform: LayoutZone { x: 0.04, y: 0.6, w: 0.92, h: 0.2 },
            title: LayoutZone { x: 0.1, y: 0.36, w: 0.8, h: 0.12 },
            avatar: Some(LayoutZone { x: 0.35, y: 0.07, w: 0.3, h: 0.3 }),
            subtitle: Some(LayoutZone { x: 0.04, y: 0.83, w: 0.92, h: 0.1 }),
        },
        "karaoke" => LayoutZones {
            waveform: LayoutZone { x: 0.04, y: 0.78, w: 0.92, h: 0.1 },
            title: LayoutZone { x: 0.06, y: 0.22, w: 0.88, h: 0.56 },
            avatar: None,
            subtitle: None,
        },
        "brand" => LayoutZones {
            waveform: LayoutZone { x: 0.55, y: 0.12, w: 0.42, h: 0.76 },
            title: LayoutZone { x: 0.24, y: 0.36, w: 0.32, h: 0.28 },
            avatar: Some(LayoutZone { x: 0.04, y: 0.36, w: 0.16, h: 0.28 }),
            subtitle: None,
        },
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_gen_is_fresh() {
        assert_eq!(WAVE_BARS, 64);
        assert_eq!(BAR_FILL, 0.64);
        assert_eq!(GAP_FILL, 0.36);
        assert_eq!(EQ_BANDS, 40);
        assert_eq!(EQ_BPS, 30);
        assert_eq!(WAVE_BPS, 120);
        assert_eq!(BG_DARK_TOP, 0.22);
        assert_eq!(BG_DARK_BOTTOM, 0.5);
        assert_eq!(SPLIT_BPS, 30);
    }
}
