// GENERATED by contract/codegen.mjs — edit contract/scene_schema.json instead,
// then run `npm run contract:gen` from the repo root.
// Imported by apps/desktop/src/types.ts and packages/wave-effects as needed.

// ── Core geometry ──────────────────────────────────────────────────────────

export interface Transform {
  x: number        // fraction 0–1 of canvas width
  y: number        // fraction 0–1 of canvas height
  w: number        // fraction 0–1 of canvas width
  h: number        // fraction 0–1 of canvas height
  rotation?: number  // degrees, default 0
  opacity?: number   // 0–1, default 1
}

// ── Animation ──────────────────────────────────────────────────────────────

export type AnimationId = 'fade' | 'slide-up' | 'slide-down' | 'scale-in'
export type Easing = 'linear' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'hold'
export type KeyframeProperty = 'x' | 'y' | 'w' | 'h' | 'rotation' | 'opacity'

export interface AnimationClip {
  preset: AnimationId
  duration: number  // seconds
}

export interface Keyframe {
  t: number                 // absolute time in seconds
  value: number | string
  easing: Easing
}

export interface KeyframeTrack {
  property: KeyframeProperty
  keyframes: Keyframe[]
}

// ── Props per node type ────────────────────────────────────────────────────

export type TextRole = 'title' | 'subtitle' | 'caption' | 'freeform'
export type ImageFit = 'cover' | 'contain'
export type ImageShape = 'rect' | 'circle' | 'rounded'
export type TextAlign = 'left' | 'center' | 'right'

export interface WaveformProps {
  style: string       // WaveStyle — kept as string to avoid circular dep with wave-effects
  color: string       // hex
}

export interface TextProps {
  text: string
  role: TextRole
  /** When true the node's text is replaced at render time by the active transcript segment.
   *  Used for captions — replaces the old libass burn-in path (Phase 5 T14). */
  boundToTranscript?: boolean
  color: string
  font: string
  size: number        // px at 1080p canvas height
  align: TextAlign
  bold: boolean
  italic: boolean
}

export interface ImageProps {
  src: string         // absolute path or app-scheme URL
  fit: ImageFit
  shape?: ImageShape
}

export interface StickerProps {
  assetId: string     // key into built-in sticker bundle (Phase 5 T15)
}

export interface VideoProps {
  src: string         // absolute path
  fit: ImageFit
  loop: boolean
  readonly muted: true  // always true — video background is decorative only
}

// ── The node ───────────────────────────────────────────────────────────────

export type SceneNodeType = 'waveform' | 'text' | 'image' | 'sticker' | 'video' | 'group'

export type SceneNodeProps = WaveformProps | TextProps | ImageProps | StickerProps | VideoProps

export interface SceneNode {
  id: string
  type: SceneNodeType
  /** Id of parent group node. Absent = root level.
   *  Children are derived by `nodes.filter(n => n.parentId === group.id)`
   *  — no `children[]` array to avoid dual source-of-truth. */
  parentId?: string
  transform: Transform
  z: number
  /** Primary show/hide window. Absent = node is visible for the entire video. */
  timing?: { start: number; end: number }
  /** Entry animation, applied over [timing.start, timing.start + animIn.duration]. */
  animIn?: AnimationClip
  /** Exit animation, applied over [timing.end - animOut.duration, timing.end]. */
  animOut?: AnimationClip
  /** Advanced continuous property animation. NOT the mechanism for simple show/hide. */
  keyframes?: KeyframeTrack[]
  /** Absent for group nodes (groups only compose children transforms). */
  props?: SceneNodeProps
}
