// ESLint flat config.
//
// Beyond baseline JS/TS correctness, this enforces the architecture boundaries
// from TECH_ARCHITECTURE.md §2.2 via `import/no-restricted-paths`. The zones
// below reference directories that don't exist yet (ui/, domain/, core/,
// store/, features/) — they're declared now so the rule takes effect
// automatically as those directories are populated in later Phase 1 tasks,
// instead of being bolted on retroactively.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import importPlugin from 'eslint-plugin-import'

// Known feature slices per TECH_ARCHITECTURE §2.2 — features must not import
// each other directly; they communicate through the store.
const FEATURES = ['start', 'studio', 'design', 'captions', 'transport', 'export', 'preview']

export default tseslint.config(
  {
    // bindings.gen.ts is regenerated by tauri-specta on every `cargo run`
    // (T8) — it's not source we own, and it already carries its own
    // @ts-nocheck header, so it shouldn't be linted at all.
    ignores: ['dist/**', 'src-tauri/**', 'node_modules/**', 'src/core/ipc/bindings.gen.ts'],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  importPlugin.flatConfigs.recommended,
  importPlugin.flatConfigs.typescript,

  {
    rules: {
      // Legacy components (pre-Phase-1) are messy by design — surface these
      // as signal, not as a wall that blocks every other task's lint gate.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-unused-expressions': ['error', {
        allowShortCircuit: true, // `cond && doThing()`
        allowTernary: true,      // `cond ? doThing() : doOtherThing()` used for its side effect
      }],
      'import/no-unresolved': 'off', // vite/tauri virtual specifiers trip this up; tsc already covers resolution
      'import/named': 'off', // duplicates tsc's own type-checking, prone to false positives on re-exports

      // The one rule this config exists for: architecture boundaries.
      'import/no-restricted-paths': ['error', {
        zones: [
          {
            target: './src/ui/**/*',
            from: ['./src/store/**/*', './src/features/**/*', './src/core/**/*', './src/app/**/*'],
            message: 'ui/ is a dumb primitive layer — it must not depend on store, features, core, or app.',
          },
          {
            target: './src/domain/**/*',
            from: ['./src/store/**/*', './src/features/**/*', './src/core/**/*', './src/app/**/*', './src/ui/**/*'],
            message: 'domain/ must stay pure TypeScript with zero app dependencies — it is the layer everything else is tested against.',
          },
          {
            target: './src/core/**/*',
            from: ['./src/features/**/*', './src/app/**/*', './src/store/**/*'],
            message: 'core/ is app infrastructure below the store/features layer — it must not depend on them.',
          },
          {
            target: './src/extensions/**/*',
            from: ['./src/store/**/*', './src/features/**/*', './src/app/**/*'],
            message: 'extensions/ (TECH_ARCHITECTURE §3.1 "Cấp 0") sits below store — it must not depend on store, features, or app.',
          },
          // `preview` is a shared leaf feature (PHASE2_TASKS.md T2 step 4):
          // it renders the canvas every other feature needs to show
          // (galleries, canvas stage, thumbnails, export preview), and it
          // imports no feature itself — so every feature may import it, the
          // one exception to the "no cross-feature import" rule below.
          ...FEATURES.map(f => ({
            target: `./src/features/${f}/**/*`,
            from: FEATURES.filter(x => x !== f && x !== 'preview').map(x => `./src/features/${x}/**/*`),
            message: `features/${f} must not import another feature directly (except features/preview) — route shared state through the store.`,
          })),
        ],
      }],

      // Direct Tauri IPC calls belong in core/ipc only, so the rest of the
      // app talks to one typed facade instead of scattering invoke() calls.
      // A hard error repo-wide (P3-T13) — the two legacy components that
      // needed the `warn` grandfather clause (StepTranscript/StepExport)
      // are gone.
      'no-restricted-imports': ['error', {
        paths: [{
          name: '@tauri-apps/api/core',
          message: 'Import from core/ipc instead of calling @tauri-apps/api/core directly (TECH_ARCHITECTURE §2.3).',
        }],
      }],
    },
  },

  // core/ (including core/ipc, the one place allowed to touch the raw Tauri
  // API) fully replaces the base tauri-import ban above with a React ban
  // instead — core/ is non-UI app infrastructure.
  {
    files: ['src/core/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [{ name: 'react', message: 'core/ is non-UI app infrastructure — it must not depend on React.' }],
      }],
    },
  },

  // __gallery__.tsx is a QA-only route (P1-T4), not a real ui/ primitive —
  // it's allowed to reach into features/ to preview things like the
  // template thumbnails/wave mini previews (P2-T3) that live there.
  {
    files: ['src/ui/__gallery__.tsx'],
    rules: {
      'import/no-restricted-paths': 'off',
    },
  },
)
